---
rsyslog_rsyslog_enable_tls: true
rsyslog_rsyslog_tls_ca_path: "/etc/ssl/certs/chained-ca.sha256.4096.crt"
rsyslog_rsyslog_tls_cert_path: "/etc/ssl/certs/{{ ansible_hostname }}.superprivyhosting.com.sha256.4096.crt"
rsyslog_rsyslog_tls_key_path: "/etc/ssl/private/{{ ansible_hostname }}.superprivyhosting.com.sha256.4096.key"
rsyslog_rsyslog_collector_dns_name: "main01.superprivyhosting.com"
rsyslog_rsyslog_collector_host_name: "main01.{{ ( 'docker' in inventory_hostname ) | ternary('docker','vm') }}.localhost"
rsyslog_rsyslog_d_files:
      10-forward-all-logs-to-collector:
        settings:

          # make gtls driver the default
          - $DefaultNetstreamDriver gtls

          - $DefaultNetstreamDriverCAFile {{ rsyslog_rsyslog_tls_ca_path }}
          - $DefaultNetstreamDriverCertFile {{ rsyslog_rsyslog_tls_cert_path }}
          - $DefaultNetstreamDriverKeyFile {{ rsyslog_rsyslog_tls_key_path }}
          - $ActionSendStreamDriverAuthMode x509/name
          - $ActionSendStreamDriverPermittedPeer {{rsyslog_rsyslog_collector_dns_name}}
          - $ActionSendStreamDriverMode 1 # run driver in TLS-only mode
          - $WorkDirectory /var/spool/rsyslog # default location for work (spool) files
          - $ActionQueueType LinkedList # use asynchronous processing
          - $ActionQueueFileName srvrfwd # set file name, also enables disk mode
          - $ActionResumeRetryCount -1 # infinite retries on insert failure
          - $ActionQueueSaveOnShutdown on # save in-memory data if rsyslog shuts down
          - "*.* @@{{ rsyslog_rsyslog_collector_host_name}}:10514"
rsyslog_repeated_msg_reduction: true
rsyslog_file_owner: root
rsyslog_file_group: adm
rsyslog_file_create_mode: '0640'
rsyslog_dir_create_mode: '0755'
rsyslog_umask: '0022'
#rsyslog_priv_drop_to_user: syslog
#rsyslog_priv_drop_to_group: syslog
