---

# certificate requests
simplepki_user_certs: []

# revocation list
simplepki_revocation_list: []

# DN settings
simplepki_domainComponent_tld: "net"
simplepki_domainComponent_domain: "superprivyhosting"
simplepki_organizationName: "superprivyhosting"

# base path for the pki
simplepki_base_dir: "/root/pki"

simplepki_key_size: "4096"

simplepki_fetch_pki_users: false
simplepki_fetch_pki_ca: true
simplepki_fetch_pki_servers: true
simplepki_dest_dir: "{{ inventory_dir }}/../secret"
simplepki_server_certs: [ { fqdn: 'srv01.superprivyhosting.com' }, { fqdn: 'srv02.superprivyhosting.com' }, { fqdn: 'main01.superprivyhosting.com' } ]

